name: CI

on: 
  repository_dispatch:
    types: manual-trigger
  push:

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install
      run: |
        echo "Installing"
    - name: Test
      run: |
        echo "Testing"
